import test from 'node:test';
import assert from 'node:assert/strict';
import { makeTemplatePack, syncTemplateCards } from '../shared/template.mjs';
const brand = { name: '카페', tagline: '편안한 하루', instagram: '@cafe', location: '서울', color: '#254a3b' };
const brief = { productName: '라떼', description: '고소한 한 잔', price: '5000', tone: 'warm', goal: 'new' };
const images = [{id:'photo',name:'사진',dataUrl:'/photo.jpg'}];
const update = (pack, patch, extra = {}) => syncTemplateCards({ pack, brand, previousBrief: brief, brief: {...brief,...patch}, images, ...extra });

test('template inputs immediately update generated card copy and retain layout, image, style and card IDs', () => {
  const pack = makeTemplatePack({brand,brief,images});
  pack.cards[0] = {...pack.cards[0],layout:'menu',imageId:'edited-photo',style:{fontScale:1.1}};
  const next = update(pack,{productName:'아인슈페너',description:'달콤한 크림',price:'6500',goal:'event',tone:'simple'});
  const expected = makeTemplatePack({brand,brief:{...brief,productName:'아인슈페너',description:'달콤한 크림',price:'6500',goal:'event',tone:'simple'},images});
  for(let i=0;i<3;i++) for(const field of ['title','subtitle','eyebrow','body']) assert.equal(next.cards[i][field],expected.cards[i][field]);
  assert.equal(next.cards[0].layout,'menu');assert.equal(next.cards[0].imageId,'edited-photo');assert.deepEqual(next.cards[0].style,{fontScale:1.1});
  assert.deepEqual(next.cards.map(c=>c.id),pack.cards.map(c=>c.id));
  assert.equal(next.caption,pack.caption);assert.equal(next.schedule,pack.schedule);
});
test('manual card copy and added cards survive input changes and reordered cards update by ID', () => {
  const pack = makeTemplatePack({brand,brief,images});
  pack.cards[0].title='직접 고친 제목';pack.cards[1].body='';
  const extra = {...pack.cards[0],id:'custom-card'};pack.cards=[pack.cards[2],pack.cards[0],extra,pack.cards[1]];
  const next=update(pack,{productName:'콜드브루',description:'시원한 커피'});
  assert.equal(next.cards[1].title,'직접 고친 제목');assert.equal(next.cards[3].body,'');assert.equal(next.cards[2],extra);
  assert.match(next.cards[0].title,/콜드브루/);assert.match(next.cards[1].body,/시원한 커피/);
});
test('new empty content follows the same template baseline from the first keystroke', () => {
  const emptyBrief={...brief,productName:'',description:'',price:'',includeSchedule:false,scheduleStartDate:''};
  const pack=makeTemplatePack({brand,brief:emptyBrief,images:[]});
  const nextBrief={...emptyBrief,productName:'콜드브루'};
  const next=syncTemplateCards({pack,brand,previousBrief:emptyBrief,brief:nextBrief,images:[]});
  assert.deepEqual(next.cards,makeTemplatePack({brand,brief:nextBrief,images:[]}).cards);
});
test('intentionally cleared text stays blank across subsequent edits and a persisted reload', () => {
  const pack=update(makeTemplatePack({brand,brief,images}),{description:'첫 번째 설명'});
  pack.cards[0].body='';
  const reloaded=JSON.parse(JSON.stringify(pack));
  const next=syncTemplateCards({pack:reloaded,brand,previousBrief:{...brief,description:'첫 번째 설명'},brief:{...brief,description:'두 번째 설명'},images});
  assert.equal(next.cards[0].body,'');
  assert.match(next.cards[1].body,/두 번째 설명/);
});
test('AI content is not regenerated by brief edits and unrelated schedule fields leave card copy alone', () => {
  const pack=makeTemplatePack({brand,brief,images});const ai={...pack,source:'ai'};
  assert.equal(update(ai,{productName:'새 메뉴'}),ai);
  const next=update(pack,{includeSchedule:true,scheduleStartDate:'2026-09-10'});
  assert.ok(next.cards.every((c,i)=>c===pack.cards[i]));
});
